---
title: "vSLAM"
subtitle: "An interactive guide to Visual Simultaneous Location And Mapping"
author: "Theodor Peifer, Amelie Hora, Japheth Legesse"
jupyter: python3
bibliography: references.bib
---

## Abstract
Visual SLAM (Simultaneous Localization and Mapping) is a computer vision technique that allows a camera to estimate its motion while simultaneously building a 3D map of an unknown environment. It works by detecting and tracking visual features across images, estimating camera movement between frames, and reconstructing scene structure from multiple views. VSLAM is widely used in robotics, augmented reality, and autonomous navigation as a lightweight alternative to depth sensors.


## Introduction
Visual SLAM estimates camera motion and reconstructs a 3D map simultaneously. There are many different algorithms and approaches yet the general pipeline looks like this:

```{=html}
<iframe src="pages/html/vslam_pipeline.html" width="100%" height="975px" frameborder="0" scrolling="no"></iframe>
```

In the next section we will dive deeper into the specific steps.

## Pipeline

### 1. Feature Detection

{{< include pages/01-feature-detection.qmd >}}

---

### 2. Feature Matching

{{< include pages/02-feature-matching.qmd >}}

---

### 3. Camera Motion Estimation

{{< include pages/03-motion.qmd >}}

---

### 4. Triangulation

{{< include pages/04-triangulation.qmd >}}

---

### 5. Sparse Point Cloud Map

{{< include pages/05-pointcloud.qmd >}}